#!/usr/bin/env bash
# Display PID and full path of all processes whose name contains "bash"

# shellcheck disable=SC2009
for pid in $(pgrep -x bash); do
    exe_path=$(readlink -f "/proc/$pid/exe")
    echo "$pid $exe_path"
done
