#!/usr/bin/env bash
# Infinite loop that handles SIGTERM and prints "I am invincible!!!"

# Trap SIGTERM, print the message, and output OK
trap 'echo "I am invincible!!!"; echo "OK"' SIGTERM

# Infinite loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done
